---
 - name: Figure out if we're on Arch or Debian based distro
   hosts: all
   tasks:
     - name: Classify hosts depending on their OS distribution
       group_by:
         key: os_{{ ansible_facts['os_family'] }}

 - name: Install Arch packages
   hosts: os_Archlinux
   connection: local
   gather_facts: False
   tasks:
     - name: Test running stuff on Arch only
       debug: 
         msg: "I'm on Arch"
   
   roles:
    - arch

 - name: Install Debian packages
   hosts: os_Debian
   connection: local
   gather_facts: False
   tasks:
     - name: Test running stuff on Arch only
       debug: 
         msg: "I'm on Debian"
   
   roles:
    - ubuntu

 - name: Do common distro stuff
   hosts: all
   roles:
    - bash
    - common
    - config
