---
- hosts: local

  tasks:
  
  - name: Download xmind zip
    get_url:
      url: https://www.xmind.net/xmind/downloads/xmind-8-update7-linux.zip
      dest: ~/downloads/xmind-8-update7-linux.zip

  - name: Create directory for xmind installation
    become: true
    file:
      path: /opt/xmind
      state: directory

  - name: Unzip xmind package to /opt
    become: true
    unarchive: 
      src: ~/downloads/xmind-8-update7-linux.zip
      dest: /opt/xmind/

  - name: Run setup.sh from xmind directory
    become: true
    async: 900
    poll: 30
    expect: 
      command: /opt/xmind/setup.sh
      responses: 
        Do you want to continue.*: "Y"

  - name: Make configuration directory writeable
    become: true
    file:
      path: /opt/xmind/XMind_amd64/configuration/
      mode: a+rwx

  - name: Copy XMind.ini file from Ansible dir to XMind directory
    become: true
    command: cp config/xmind/XMind.ini /opt/xmind/XMind_amd64/XMind.ini




