packages:
- ansible
- cmatrix
- cowsay
- gimp
- git
- gnubg
- htop
- iftop
- jq
- sl
- steam
- terminator
- tmux
- tree
- vim
- vagrant
- virtualbox
- wavemon
- connman
- jupyterlab
- xorg-xbacklight
- dvd+rw-tools
- inxi
- mesa-demos
- dstat
- sysstat
- acpi
- gdb
- calibre
- speedtest-cli
- hsetroot
- picom
- noto-fonts-emoji
- bat
- ranger


apt_packages:
- fortune
- fortune-anarchism
- fortunes-bofh-excuses
- fortunes-off
- fortunes-spam
- openjdk-11-jdk
- snapcraft
- toilet

pacman_packages:
- fortune-mod
- jdk-openjdk
- banner

