---
# This is borked currently. Getting Python AttributeError. Known bug. Have to run pacman update/upgrade manually for now
#- name: Pacman - Upgrade all packages to the latest version
#become: true
#pacman:
#update_cache: yes
#upgrade: yes

- name: Pacman - Install packages common to apt and pacman
  become: true
  pacman:
    name: "{{ packages }}"

- name: Pacman - Install pacman-only packages
  become: true
  pacman:
    name: "{{ pacman_packages }}"
