- name: Setup Vim - Check .vimrc exists
  stat: path=~/.vimrc
  register: vimrcfilecheck

- name: Setup Vim - Move .vimrc to backup
  command: mv ~/.vimrc ~/.vimrc.{{ ansible_date_time.date }}-{{ ansible_date_time.time }}
  when: vimrcfilecheck.stat.exists

- name: Setup Vim - Copy vimrc from Ansible dir to HOME
  command: cp "{{ role_path }}/files/vim/vimrc" ~/.vimrc
