---
- name: Apt - Upgrade all packages to the latest version
  become: true
  apt:
    update_cache: yes
    upgrade: yes
  when: ansible_os_family == 'Debian'

- name: Apt - Install common apt and pacman packages
  become: true
  apt:
    name: "{{ packages }}"
  when: ansible_os_family == 'Debian'

- name: Apt - Install apt-only packages
  become: true
  apt:
    name: "{{ apt_packages }}"
  when: ansible_os_family == 'Debian'

# This is borked currently. Getting Python AttributeError. Known bug. Have to run pacman update/upgrade manually for now
#- name: Pacman - Upgrade all packages to the latest version
#become: true
#pacman:
#update_cache: yes
#upgrade: yes

- name: Pacman - Install packages common to apt and pacman
  become: true
  pacman:
    name: "{{ packages }}"
  when: ansible_os_family == 'Archlinux'

- name: Pacman - Install pacman-only packages
  become: true
  pacman:
    name: "{{ pacman_packages }}"
  when: ansible_os_family == 'Archlinux'
