- name: Setup zoom - Check if zoom already installed
  become: true
  shell: pacman -Q | grep "^zoom "
  register: zoom_installed
  ignore_errors: True 


- name: Setup zoom - Install zoom dependencies
  become: true
  pacman:
    name: pulseaudio-alsa

- block:
  - name: Setup zoom - Clone the Arch zoom package repo
    git:
      repo: "https://aur.archlinux.org/zoom.git"
      dest: /tmp/zoom
      clone: yes

  - name: Setup zoom - Build the AUR package
    command: makepkg -s
    args:
      chdir: /tmp/zoom/
      
  - name: Setup zoom - Get the name of the zoom AUR package
    find:
      paths: /tmp/zoom/
      patterns: "*.xz"
    register: files_matched

  - name: Setup zoom - Do the Pacman package installation
    become: true
    command: pacman -U --noconfirm "{{ item.path }}" 
    with_items: "{{ files_matched.files }}"

  - name: Setup zoom - Remove the zoom download directory
    file:
      path: /tmp/zoom/
      state: absent
  when: zoom_installed.stdout == "" 
