- name: Aptitude - Check Google apt file exists
  become: true
  command: test -f {{chrome_apt_file}}
  register: google_apt_exists
  ignore_errors: True

- block:
  - name: Aptitude - Add Google Chrome key
    uri: 
      url: https://dl-ssl.google.com/linux/linux_signing_key.pub
      return_content: yes
    register: keyresponse

  - name: Fail if response isn't a PGP key
    fail:
    when: "'BEGIN PGP PUBLIC KEY BLOCK' not in keyresponse.content"

  - name: Add key to apt cache
    become: true
    shell: echo "{{keyresponse.content}}" | apt-key add -

  - name: Aptitude - Add Google Chrome repo
    become: true
    copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest={{chrome_apt_file}} owner=root group=root mode=644

  - name: Aptitude - Update apt cache
    become: true
    apt: update_cache=yes

  - name: Aptitude - Install Google Chrome
    become: true
    apt: pkg=google-chrome-stable state=present
  when: google_apt_exists.rc == 1

- name: Setup Chrome - Make chrome default browser
  shell: xdg-settings set default-web-browser google-chrome.desktop 
