- name: Setup icaclient - Check if icaclient already installed
  become: true
  shell: pacman -Q | grep "icaclient"
  register: icaclient_installed
  ignore_errors: True 

- name: Setup icaclient - Install dependencies
  become: true
  pacman:
    name: libpng12,libxp,libjpeg6-turbo,libidn11 

- block:
  - name: Setup icaclient - Clone the Arch icaclient package repo
    git:
      repo: "https://aur.archlinux.org/icaclient.git"
      dest: /tmp/icaclient
      clone: yes

  - name: Setup icaclient - Build the AUR package
    command: makepkg -fs
    args:
      chdir: /tmp/icaclient/
      
  - name: Setup icaclient - Get the name of the icaclient AUR package
    find:
      paths: /tmp/icaclient/
      patterns: "*.xz"
    register: files_matched

  - name: Setup icaclient - Do the Pacman package installation
    become: true
    command: pacman -U --noconfirm "{{ item.path }}" 
    with_items: "{{ files_matched.files }}"

  - name: Setup icaclient - Remove the icaclient download directory
    file:
      path: /tmp/icaclient/
      state: absent
  when: icaclient_installed.stdout == "" 
