---
- hosts: local

  tasks: 
  
  - name: Check blueman autostart file exists
    become: true
    stat: path=/etc/xdg/autostart/blueman.desktop
    register: filecheck

  - name: Move blueman autostart file to backup
    become: true
    command: mv /etc/xdg/autostart/blueman.desktop /etc/xdg/autostart/blueman.desktop.{{ ansible_date_time.date }}-{{ ansible_date_time.time }}
    when: filecheck.stat.exists
