---
- import_playbook: bash/configure-bash.yml
- import_playbook: ubuntu/configure-apport.yml
- import_playbook: ubuntu/configure-xdg.yml
- import_playbook: general/configure-keymap.yml

- import_playbook: packages/install-aptitude.yml
- import_playbook: packages/install-chrome.yml
- import_playbook: packages/install-desktop-envs.yml
- import_playbook: packages/install-git.yml
- import_playbook: packages/install-terminator.yml
- import_playbook: packages/install-tmux.yml
- import_playbook: packages/install-tree.yml
- import_playbook: packages/install-vim.yml
