---
- hosts: local

  tasks: 
  - name: Aptitude - Install terminator
    become: true
    apt:
      name: terminator

  - name: Setup terminator - Check terminator config exists
    stat: path=~/.config/terminator/config
    register: terminatorfilecheck

  - name: Setup terminator - Move terminator config to backup
    command: mv ~/.config/terminator/config  ~/.config/terminator/config.{{ ansible_date_time.date }}-{{ ansible_date_time.time }}
    when: terminatorfilecheck.stat.exists

  - name: Setup terminator - Copy terminator config file from Ansible dir to HOME
    command: cp config/terminator/config ~/.config/terminator/config
