---
- hosts: local

  tasks: 
  - name: Setup vundle - Check .vimrc exists
    stat: path=~/.vimrc
    register: vimrcfilecheck

  - name: Setup vundle - Check .vim exists
    stat: path=~/.vim
    register: vimfilecheck

  - name: Setup vundle - Move .vimrc to backup
    command: mv ~/.vimrc ~/.vimrc.{{ ansible_date_time.date }}-{{ ansible_date_time.time }}
    when: vimrcfilecheck.stat.exists

  - name: Setup vundle - Move .vim to backup
    command: mv ~/.vim ~/.vim.{{ ansible_date_time.date }}-{{ ansible_date_time.time }}
    when: vimfilecheck.stat.exists

  - name: Setup vundle - Clone the vundle repo
    git:
      repo: "https://github.com/gmarik/vundle.git"
      dest: ~/.vim/bundle/vundle
      clone: yes
      update: yes

  - name: Setup vundle - Copy vimrc from Ansible dir to HOME
    command: cp config/vim/vimrc ~/.vimrc
